version: '2'

services:
  bookx:
    build:
      context: .
    container_name: bookx
    environment:
      - BOOKX_DATABASE_IP=cassandra
      - BOOKX_PORT=${BOOKX_PORT}
    ports:
      - "${BOOKX_PORT}:${BOOKX_PORT}"
    command: ["./wait-for-it.sh", "-t", "30", "migrations:8081", "--", "/go/bin/bookx"]
  migrations:
    image: maximep/bookx-migration
    container_name: migrations
    command: ["./wait-for-it.sh", "-t", "30", "cassandra:9042", "--", "./migrations.sh"]
    ports:
      - "8081:8081"
  cassandra:
    image: maximep/bookx-cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
      - "9160:9160"
